CREATE DATABASE SERVICEDESK;
USE SERVICEDESK;


CREATE TABLE USERSTATUS (
	ID INT IDENTITY PRIMARY KEY,
	STATUSNAME NVARCHAR(255) NOT NULL
);

CREATE TABLE ROLE (
	ID INT IDENTITY PRIMARY KEY,
	ROLENAME NVARCHAR(255) NOT NULL
);

CREATE TABLE APPUSER (
	ID INT IDENTITY PRIMARY KEY,
	ID_STATUS INT FOREIGN KEY REFERENCES USERSTATUS(ID) NOT NULL,
	ID_ROLE INT FOREIGN KEY REFERENCES ROLE(ID) NOT NULL,
	FULLNAME NVARCHAR(255) NOT NULL,
	EMAIL NVARCHAR(255) NOT NULL,
	PHONE NVARCHAR(60),
	PASSWORDHASH NVARCHAR(128) NOT NULL,
	PASSWORDSALT NVARCHAR(128) NOT NULL
);

CREATE TABLE TICKETSTATUS (
	ID INT IDENTITY PRIMARY KEY,
	STATUSNAME NVARCHAR(255) NOT NULL
);

CREATE TABLE SERVICES (
	ID INT IDENTITY PRIMARY KEY,
	SERVICENAME NVARCHAR(255) NOT NULL
);

CREATE TABLE TICKET (
	ID INT IDENTITY PRIMARY KEY,
	ID_TICKETSTATUS INT FOREIGN KEY REFERENCES TICKETSTATUS(ID) NOT NULL,
	ID_SERVICE INT FOREIGN KEY REFERENCES SERVICES(ID) NOT NULL,
	CREATEDBY INT FOREIGN KEY REFERENCES APPUSER(ID) NOT NULL,
	CREATEDATE DATETIME DEFAULT GETDATE(),
	LASTMODIFIEDDATE DATETIME DEFAULT GETDATE(),
	ATTACHMENTS NVARCHAR(MAX),
	SUBJECT NVARCHAR(255) NOT NULL,
	DESCRIPTION NVARCHAR(255)
);

CREATE TABLE COMMENTTYPE (
	ID INT IDENTITY PRIMARY KEY,
	COMMENTTYPENAME NVARCHAR(255) NOT NULL
);

CREATE TABLE LEVELOFSATISFACTION (
	ID INT IDENTITY PRIMARY KEY,
	LEVELOFSATISFACTION INT NOT NULL
);

CREATE TABLE COMMENT (
	ID INT IDENTITY PRIMARY KEY,
	CREATEDBY INT FOREIGN KEY REFERENCES APPUSER(ID) NOT NULL,
	ID_TICKET INT FOREIGN KEY REFERENCES TICKET(ID) NOT NULL,
	COMMENTTEXT NVARCHAR(255) NOT NULL,
	CREATEDATE DATETIME DEFAULT GETDATE()
);

INSERT INTO ROLE(ROLENAME) values ('Usuario'), ('Agente'), ('Administrador');
INSERT INTO USERSTATUS (STATUSNAME) VALUES('Activo'),('Inactivo');
INSERT INTO TICKETSTATUS(STATUSNAME) VALUES ('Abierto'),('En proceso'),('Finalizado');
INSERT INTO SERVICES(Servicename) VALUES ('Cambio de hardware'), ('Correo electrónico'), ('Carpetas compartidas'), ('Telefonía IP');
INSERT INTO LEVELOFSATISFACTION(LEVELOFSATISFACTION) VALUES (1), (2), (3), (4), (5);
INSERT INTO COMMENTTYPE(COMMENTTYPENAME) VALUES ('Respuesta'), ('Cierre'),('Calificación');
-- password for user is prueba
INSERT INTO APPUSER(ID_STATUS, ID_ROLE, FULLNAME, EMAIL, PHONE, PASSWORDHASH, PASSWORDSALT)
VALUES (1,3,'Test User', 'test@test.com','12345678', 'SEBkD1WPcQhpCI7muD4jp97hIaRuiuSY0UuDLsHsRNp857u7u6UqlpJs0MGT0irFdf2EsMwQc7F7wk/kjFgJ7q52JIE5AQ==', 'ClOFWONegwMZUfYkdeq2vZ1g0tS1aXlaGw==');